-- Migration 035: Manual house agent for owner-initiated trades.
--
-- Sets up a single placeholder agent row that satisfies the
-- agent_trades.agent_id NOT NULL foreign key when a portfolio owner
-- manually sells (or buys) a position from the UI. This row is NOT an
-- autonomous agent — strategy is NULL so the heartbeat skips it.
-- It has no portfolio of its own and no cash account; it exists
-- solely as the attribution target for manual trades.
--
-- The trade tape renders these rows with the display name 'Manual'.
--
-- 90-day re-buy cooldown (the user-facing rule "having sold an equity
-- once, the system should not consider that equity for purchase within
-- the next 90 days") is enforced in the buyer strategy code, not the
-- schema — it's just a query against agent_trades with side='sell' and
-- executed_at >= now() - interval '90 days'. No DDL needed.
--
-- Additive & idempotent. Paste-and-run in the Supabase SQL editor.

INSERT INTO agents (
    handle, display_name, description, long_description,
    is_house_agent, available_for_hire, strategy, heartbeat_interval_hours,
    config, api_key_hash, api_key_prefix
) VALUES (
    'manual',
    'Manual',
    'Owner-initiated trades from the portfolio UI. Not an autonomous agent — this row exists only to satisfy the agent_trades.agent_id foreign key when an owner manually sells or buys a position.',
    $md$Placeholder agent. Never heartbeats. Used as the `agent_id` on `agent_trades` rows generated by the portfolio detail page's manual sell button.

A separate row (rather than overloading an existing agent) keeps the audit trail clean: the trade tape on `/portfolios/<slug>` clearly distinguishes "the Buying Agent decided to sell" from "the owner decided to sell" via the agent attribution.$md$,
    TRUE,
    FALSE,
    NULL,
    168,
    '{}'::jsonb,
    'house-agent',
    'ak_house_man'
)
ON CONFLICT (handle) DO NOTHING;
